Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
visualize_characteristic_time(align_time=True)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m [43mvisualize_characteristic_time[49m[43m([49m[43malign_time[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m

File [0;32m~/work/Predicting-Pulsed-Laser-Deposition-SrTiO3-Homoepitaxy-Growth-Dynamics-using-RHEED/Predicting-Pulsed-Laser-Deposition-SrTiO3-Homoepitaxy-Growth-Dynamics-using-RHEED/src/sto_rheed/Packed_functions.py:181[0m, in [0;36mvisualize_characteristic_time[0;34m(align_time, normalize)[0m
[1;32m    178[0m fig, axes [38;5;241m=[39m layout_fig([38;5;241m3[39m, [38;5;241m1[39m, figsize[38;5;241m=[39m([38;5;241m8[39m, [38;5;241m8[39m))
[1;32m    179[0m ax1, ax3, ax5 [38;5;241m=[39m axes[[38;5;241m0[39m], axes[[38;5;241m1[39m], axes[[38;5;241m2[39m]
[0;32m--> 181[0m x_all_sample1, y_all_sample1 [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m../Data/Plume_results/treated_213nm-x_all.npy[39;49m[38;5;124;43m'[39;49m[43m)[49m, np[38;5;241m.[39mload([38;5;124m'[39m[38;5;124m../Data/Plume_results/treated_213nm-y_all.npy[39m[38;5;124m'[39m)
[1;32m    182[0m x_sklearn_sample1, tau_sklearn_sample1 [38;5;241m=[39m np[38;5;241m.[39mswapaxes(np[38;5;241m.[39mload([38;5;124m'[39m[38;5;124m../Data/Plume_results/treated_213nm-fitting_results(sklearn).npy[39m[38;5;124m'[39m), [38;5;241m0[39m, [38;5;241m1[39m)[[[38;5;241m0[39m, [38;5;241m-[39m[38;5;241m1[39m]]
[1;32m    183[0m bg_growth_sample1 [38;5;241m=[39m np[38;5;241m.[39mload([38;5;124m'[39m[38;5;124m../Data/Plume_results/treated_213nm-bg_growth.npy[39m[38;5;124m'[39m)

File [0;32m~/.local/lib/python3.12/site-packages/numpy/lib/npyio.py:427[0m, in [0;36mload[0;34m(file, mmap_mode, allow_pickle, fix_imports, encoding, max_header_size)[0m
[1;32m    425[0m     own_fid [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[1;32m    426[0m [38;5;28;01melse[39;00m:
[0;32m--> 427[0m     fid [38;5;241m=[39m stack[38;5;241m.[39menter_context([38;5;28;43mopen[39;49m[43m([49m[43mos_fspath[49m[43m([49m[43mfile[49m[43m)[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m)[49m)
[1;32m    428[0m     own_fid [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m    430[0m [38;5;66;03m# Code to distinguish from NumPy binary files and pickles.[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../Data/Plume_results/treated_213nm-x_all.npy'

