Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%load_ext autoreload
%autoreload 2
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import colors
import seaborn as sns

from viz.style import set_style
from viz.printing import printer
from viz.layout import layout_fig
from sto_rheed.Dataset import RHEED_parameter_dataset
from sto_rheed.Viz import Viz
from sto_rheed.Analysis import analyze_curves, remove_outlier, smooth
from sto_rheed.Packed_functions import visualize_characteristic_time, violinplot_characteristic_time
from sto_rheed.Fit import NormalizeData

printing = printer(basepath = '../Figures/4.Characteristic_time/')
printing_plot = printer(basepath = '../Figures/4.Characteristic_time/', fileformats=['png', 'svg', 'tif'], dpi=600)

set_style("printing")

seq_colors = ['#00429d','#2e59a8','#4771b2','#5d8abd','#73a2c6','#8abccf','#a5d5d8','#c5eddf','#ffffe0']
bgc1, bgc2 = colors.hex2color(seq_colors[0]), colors.hex2color(seq_colors[5])
color_blue = (44/255,123/255,182/255)
color_orange = (217/255,95/255,2/255)
color_purple = (117/255,112/255,179/255)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 8[0m
[1;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m colors
[1;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mseaborn[39;00m [38;5;28;01mas[39;00m [38;5;21;01msns[39;00m
[0;32m----> 8[0m [38;5;28;01mfrom[39;00m [38;5;21;01mviz[39;00m[38;5;21;01m.[39;00m[38;5;21;01mstyle[39;00m [38;5;28;01mimport[39;00m set_style
[1;32m      9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mviz[39;00m[38;5;21;01m.[39;00m[38;5;21;01mprinting[39;00m [38;5;28;01mimport[39;00m printer
[1;32m     10[0m [38;5;28;01mfrom[39;00m [38;5;21;01mviz[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlayout[39;00m [38;5;28;01mimport[39;00m layout_fig

[0;31mModuleNotFoundError[0m: No module named 'viz'

